using CommandLine;
using CommandLine.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TSGSystemsToolkit.CmdLine.Options
{
    [Verb("pse", HelpText = "Tools for working with the reports generated by Petrol Server")]
    public class PseOptions
    {
        [Option('t', "terminals", SetName = "terminals",
            HelpText = "Directory path to Terminals_044.csv")]
        public string TerminalsFilePath { get; set; }

        [Option('o', "output", HelpText = "Output directory - if not specified, files will be generated in the same directory as any input file.")]
        public string OutputPath { get; set; }

        [Option('e', "emisfile", HelpText = "Create a Remote eMIS site-list file. If no output path is specified, will deploy the file directly to its location" +
            " in your AppData folder.", SetName = "terminals")]
        public bool CreateEmisFile { get; set; }

        [Usage(ApplicationAlias = "systk")]
        public static IEnumerable<Example> Examples
        {
            get
            {
                return new List<Example>()
                {
                    new Example("Create a new Remote eMIS station list file - if no output is defined, will automatically place in the correct folder on your PC",
                        new PseOptions {TerminalsFilePath = "C:\\Path\\To Your\\Terminals File", CreateEmisFile = true})
                };
            }
        }
    }
}
